### PR TITLE
Update CSSLint to v1.0.0.

### PR DESCRIPTION
**Pull request by XhmikosR**
Needs changelog and the appropriate version bump.

### CODE REVIEW

**Comment by vladikoff** [comment]
woohoo!

**Comment by XhmikosR** [comment]
@vladikoff: can you suggest a solution for the tests so that they don't fail yet show as passing?

**Comment by vladikoff** [comment]
@XhmikosR they were warnings though no? I thought everyone wanted the CSSLint task to throw errors but just log warnings

**Comment by XhmikosR** [comment]
I find the current solution confusing personally. Because errors will only be parsing errors and everything else a warning. So it's warnings that makes sense to see too.

**Comment by XhmikosR** [comment]
Also, `>> ERROR: Unexpected token '12p' at line 3, col 19. This rule looks for recoverable syntax errors. (errors) Browsers: All` yet the tests are passing.

**Comment by nschonni** [comment]
Thanks @XhmikosR! Ping  me if you need any triage help

**Pull request merged**
